import { defaultTheme } from '@styles'

import { TypographyVariant, TypographyVariantName } from './types'

type TypographyVariants = Record<TypographyVariantName, TypographyVariant>

const defaultTypographyVariantStyles: TypographyVariant = {
  fontStyle: 'normal',
  transition: `all ${defaultTheme.transition.default}`,
  fontWeight: '700',
  fontFamily: 'Gilroy',
}

export const typographyVariants: TypographyVariants = {
  headlineMobileHeadline1Bold3436: {
    ...defaultTypographyVariantStyles,
    fontSize: '34px',
    lineHeight: '36px',
  },
  headlineMobileHeadline2Bold2636: {
    ...defaultTypographyVariantStyles,
    fontSize: '26px',
    lineHeight: '36px',
  },
  headlineMobileHeadline3Bold2230: {
    ...defaultTypographyVariantStyles,
    fontSize: '22px',
    lineHeight: '30px',
  },
  headlineMobileHeadline4Bold2028: {
    ...defaultTypographyVariantStyles,
    fontSize: '20px',
    lineHeight: '28px',
  },
  headlineMobileHeadline5Bold1826: {
    ...defaultTypographyVariantStyles,
    fontSize: '18px',
    lineHeight: '26px',
  },
  bodyMobileHeadlineBody1Bold1620: {
    ...defaultTypographyVariantStyles,
    fontSize: '16px',
    lineHeight: '20px',
  },
  bodyMobileHeadlineBody2Bold1616: {
    ...defaultTypographyVariantStyles,
    fontSize: '16px',
    lineHeight: '16px',
  },
  bodyMobileHeadlineBody3Medium1624: {
    ...defaultTypographyVariantStyles,
    fontWeight: '500',
    fontSize: '16px',
    lineHeight: '24px',
  },
  bodyMobileHeadlineBody4Regular1620: {
    ...defaultTypographyVariantStyles,
    fontWeight: '400',
    fontSize: '16px',
    lineHeight: '20px',
  },
  bodyMobileHeadlineBody5Bold1422: {
    ...defaultTypographyVariantStyles,
    fontSize: '14px',
    lineHeight: '22px',
  },
  bodyMobileHeadlineBody6Medium1418: {
    ...defaultTypographyVariantStyles,
    fontWeight: '500',
    fontSize: '14px',
    lineHeight: '18px',
  },
  bodyMobileHeadlineBody7Regular1420: {
    ...defaultTypographyVariantStyles,
    fontWeight: '400',
    fontSize: '14px',
    lineHeight: '20px',
  },
  bodyMobileHeadlineBody8Bold1220: {
    ...defaultTypographyVariantStyles,
    fontSize: '12px',
    lineHeight: '20px',
  },
  bodyMobileHeadlineBody9Medium1218: {
    ...defaultTypographyVariantStyles,
    fontWeight: '500',
    fontSize: '12px',
    lineHeight: '18px',
  },
  bodyMobileHeadlineBody10Regular1220: {
    ...defaultTypographyVariantStyles,
    fontWeight: '400',
    fontSize: '12px',
    lineHeight: '20px',
  },
  bodyMobileHeadlineBody11Medium1016: {
    ...defaultTypographyVariantStyles,
    fontWeight: '500',
    fontSize: '10px',
    lineHeight: '16px',
  },
  primaryButtonMobilePrimaryButtonLargeBold1010: {
    ...defaultTypographyVariantStyles,
    fontSize: '18px',
    lineHeight: '26px',
    letterSpacing: '-0.005em',
  },
  primaryButtonMobilePrimaryButtonMediumBold1826: {
    ...defaultTypographyVariantStyles,
    fontSize: '14px',
    lineHeight: '20px',
    letterSpacing: '-0.005em',
  },
  primaryButtonMobilePrimaryButtonSmallBold1422: {
    ...defaultTypographyVariantStyles,
    fontSize: '12px',
    lineHeight: '20px',
    letterSpacing: '-0.005em',
  },
  secondaryButtonMobileSecondaryButtonMediumSemibold1220: {
    ...defaultTypographyVariantStyles,
    fontWeight: '600',
    fontSize: '14px',
    lineHeight: '22px',
  },
  textButtonMobileTextButton1Medium1422: {
    ...defaultTypographyVariantStyles,
    fontSize: '14px',
    lineHeight: '22px',
  },
  textButtonMobileTextButton2Bold1620: {
    ...defaultTypographyVariantStyles,
    fontWeight: '600',
    fontSize: '14px',
    lineHeight: '22px',
  },
  textButtonMobileTextButton3SemiboldUnderlined1422: {
    ...defaultTypographyVariantStyles,
    fontSize: '12px',
    lineHeight: '20px',
  },
  textButtonMobileTextButton4Semibold1416: {
    ...defaultTypographyVariantStyles,
    fontWeight: '600',
    fontSize: '14px',
    lineHeight: '16px',
  },
  textButtonMobileTextButton5BoldUnderlined1220: {
    ...defaultTypographyVariantStyles,
    fontSize: '12px',
    lineHeight: '20px',
  },
  textButtonMobileTextButton6BoldUnderlined1014: {
    ...defaultTypographyVariantStyles,
    fontSize: '12px',
    lineHeight: '20px',
  },
  navigationMobileTabBarNavigationBold1018: {
    ...defaultTypographyVariantStyles,
    fontSize: '10px',
    lineHeight: '18px',
    letterSpacing: '-0.005em',
  },
  navigationMobileTabBarNavigationSemibold1018: {
    ...defaultTypographyVariantStyles,
    fontWeight: '600',
    fontSize: '10px',
    lineHeight: '18px',
    letterSpacing: '-0.005em',
  },
  tabBar10And20MobileTabBarForProfilePageAndFAQBold1422: {
    ...defaultTypographyVariantStyles,
    fontSize: '14px',
    lineHeight: '22px',
    letterSpacing: '-0.005em',
  },
  tabBar10And20MobileTabBarForProfilePageAndFAQMedium1422: {
    ...defaultTypographyVariantStyles,
    fontWeight: '500',
    fontSize: '14px',
    lineHeight: '22px',
    letterSpacing: '-0.005em',
  },
  accordionsMobileAccrodionsTitleSemibold1422: {
    ...defaultTypographyVariantStyles,
    fontWeight: '600',
    fontSize: '14px',
    lineHeight: '22px',
    letterSpacing: '-0.005em',
  },
  accordionsMobileAccrodionsTextMedium1218: {
    ...defaultTypographyVariantStyles,
    fontWeight: '500',
    fontSize: '12px',
    lineHeight: '18px',
    letterSpacing: '-0.005em',
  },
  statusMobileStatusForPetBold1422: {
    ...defaultTypographyVariantStyles,
    fontSize: '14px',
    lineHeight: '22px',
    letterSpacing: '-0.005em',
  },
  onboardingMobileOnboardingTextSemibold1216: {
    ...defaultTypographyVariantStyles,
    fontWeight: '600',
    fontSize: '12px',
    lineHeight: '16px',
    letterSpacing: '-0.005em',
  },
  chatMobileChatTextMedium1216: {
    ...defaultTypographyVariantStyles,
    fontWeight: '500',
    fontSize: '12px',
    lineHeight: '16px',
    letterSpacing: '-0.005em',
  },
  cardPetsMobileHeadlineNameBold1313: {
    ...defaultTypographyVariantStyles,
    fontSize: '13px',
    lineHeight: '13px',
    letterSpacing: '-0.005em',
  },
  cardPetsMobileHeadlinePriceSemibold1216: {
    ...defaultTypographyVariantStyles,
    fontWeight: '600',
    fontSize: '12px',
    lineHeight: '16px',
    letterSpacing: '-0.005em',
  },
  cardPetsMobileHeadlineLevelBold1111: {
    ...defaultTypographyVariantStyles,
    fontSize: '11px',
    lineHeight: '11px',
    letterSpacing: '-0.005em',
  },
  cardPetsMobileHeadlineStatusBold1016: {
    ...defaultTypographyVariantStyles,
    fontSize: '10px',
    lineHeight: '16px',
    letterSpacing: '-0.005em',
  },
  cardPetsMobileHeadlineLevelBold11119Auto: {
    ...defaultTypographyVariantStyles,
    fontSize: '9px',
    lineHeight: '11.14px',
    letterSpacing: '-0.005em',
  },
  inputMobileInput1Semibold1624: {
    ...defaultTypographyVariantStyles,
    fontWeight: '600',
    fontSize: '16px',
    lineHeight: '24px',
    letterSpacing: '-0.005em',
  },
  inputMobileInputsText2Medium1624: {
    ...defaultTypographyVariantStyles,
    fontWeight: '500',
    fontSize: '16px',
    lineHeight: '24px',
    letterSpacing: '-0.005em',
  },
  inputMobileInputsText3Medium1414: {
    ...defaultTypographyVariantStyles,
    fontWeight: '500',
    fontSize: '14px',
    lineHeight: '14px',
    letterSpacing: '-0.005em',
  },
  inputMobileInputsText4Regular1422: {
    ...defaultTypographyVariantStyles,
    fontWeight: '400',
    fontSize: '14px',
    lineHeight: '22px',
    letterSpacing: '-0.005em',
  },
  shadowTextMobileShadowText1Bold3436: {
    ...defaultTypographyVariantStyles,
    fontSize: '34px',
    lineHeight: '36px',
    letterSpacing: '-0.005em',
    boxShadow: '0px 2px 0px 0px rgba(0, 0, 0, 0.13)',
  },
  shadowTextMobileShadowText2Bold1826: {
    ...defaultTypographyVariantStyles,
    fontSize: '18px',
    lineHeight: '26px',
    letterSpacing: '-0.005em',
    boxShadow: '0px 2px 0px 0px rgba(0, 0, 0, 0.13)',
  },
  shadowTextMobileShadowText3Bold1422: {
    ...defaultTypographyVariantStyles,
    fontSize: '14px',
    lineHeight: '22px',
    letterSpacing: '-0.005em',
    boxShadow: '0px 2px 0px 0px rgba(0, 0, 0, 0.13)',
  },
  shadowTextMobileShadowText4Bold1220: {
    ...defaultTypographyVariantStyles,
    fontSize: '12px',
    lineHeight: '20px',
    letterSpacing: '-0.005em',
    boxShadow: '0px 2px 0px 0px rgba(0, 0, 0, 0.13)',
  },
  bodyMobileHeadlineBody12Semibold1010: {
    ...defaultTypographyVariantStyles,
    fontWeight: '600',
    fontSize: '10px',
    lineHeight: '10px',
  },
  cardPetsMobileHeadlineLevelBold9Auto: {
    ...defaultTypographyVariantStyles,
    fontSize: '9px',
    lineHeight: '11px',
  },
  textButtonMobileTextButton6SemiboldUnderlined1014: {
    ...defaultTypographyVariantStyles,
    fontSize: '10px',
    lineHeight: '14px',
  },
  textButtonMobileTextButton2Bold1422: {
    ...defaultTypographyVariantStyles,
    fontSize: '14px',
    lineHeight: '22px',
  },

  desktopH16060: {
    ...defaultTypographyVariantStyles,
    fontSize: '60px',
    lineHeight: '60px',
  },
  desktopH23030: {
    ...defaultTypographyVariantStyles,
    fontSize: '30px',
    lineHeight: '30px',
  },
  desktopH32225: {
    ...defaultTypographyVariantStyles,
    fontSize: '25px',
    lineHeight: '25px',
  },
  desktopH41616: {
    ...defaultTypographyVariantStyles,
    fontSize: '16px',
    lineHeight: '16px',
  },
  desktopLead1721: {
    ...defaultTypographyVariantStyles,
    fontSize: '17px',
    lineHeight: '21px',
    fontWeight: '500',
  },
  desktopBodyRegular1519: {
    ...defaultTypographyVariantStyles,
    fontSize: '15px',
    lineHeight: '19px',
    fontWeight: '400',
  },
  desktopBodyMedium1519: {
    ...defaultTypographyVariantStyles,
    fontSize: '15px',
    lineHeight: '19px',
    fontWeight: '500',
  },
  desktopBodyBold1519: {
    ...defaultTypographyVariantStyles,
    fontSize: '15px',
    lineHeight: '19px',
  },
  desktopLinkBold1515: {
    ...defaultTypographyVariantStyles,
    fontSize: '15px',
    lineHeight: '15px',
  },
  desktopButtonLPrimary1616: {
    ...defaultTypographyVariantStyles,
    fontSize: '16px',
    lineHeight: '16px',
  },
  desktopButtonMSecondary1616: {
    ...defaultTypographyVariantStyles,
    fontSize: '16px',
    lineHeight: '16px',
    fontWeight: '600',
  },
  desktopPrice1717: {
    ...defaultTypographyVariantStyles,
    fontSize: '17px',
    lineHeight: '17px',
  },
  desktopInputMedium1520: {
    ...defaultTypographyVariantStyles,
    fontSize: '15px',
    lineHeight: '20px',
    fontWeight: '500',
  },
  desktopBodySRegular1212: {
    ...defaultTypographyVariantStyles,
    fontSize: '12px',
    lineHeight: '12px',
    fontWeight: '400',
  },
  desktopBodySBold1212: {
    ...defaultTypographyVariantStyles,
    fontSize: '12px',
    lineHeight: '12px',
  },
  primaryButtonMobilePrimaryButtonLargeBold1826: {
    ...defaultTypographyVariantStyles,
    fontSize: '18px',
    lineHeight: '26px',
    letterSpacing: '-0.005em',
  },
}
